#http
services:
  app:
    image: ghcr.io/mahn-ke/wallpapers-by-vincent:latest@sha256:ffd598f716d5edcd9ded3731371694c6869a4cd3b79b6e27e5616f764c13be36
    restart: on-failure:5
    environment:
      - APP_ACCESS_TOKEN=${APP_ACCESS_TOKEN}
      - IMMICH_ALBUM_ID=${IMMICH_ALBUM_ID}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
      - IMMICH_BASE_URL=${IMMICH_BASE_URL}
    ports:
      - "3010:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
