#http
services:
  app:
    image: ghcr.io/mahn-ke/wallpapers-by-vincent:latest@sha256:779f9d360ad3e99b241e42f64367c2ba8bf1a5d3b4305f1408c8362f7f6f7807
    restart: on-failure:5
    environment:
      - APP_ACCESS_TOKEN=${APP_ACCESS_TOKEN}
      - IMMICH_ALBUM_ID=${IMMICH_ALBUM_ID}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
      - IMMICH_BASE_URL=${IMMICH_BASE_URL}
    ports:
      - "3010:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
